### ISSUE TITLE
Scaling only is triggered by node pool size change

### ISSUE THREAD

**Issue by AlexsJones** [crossplane-contrib/provider-civo#10]
```
	if len(desiredCivoCluster.Spec.Pools) != len(remoteCivoCluster.Pools) {
```

In order to fix the update mechanism to work for instance count changes within a node pool this needs modification.

**Comment by AlexsJones** [comment]
https://github.com/crossplane-contrib/provider-civo/pull/11

**Comment by exocode** [comment]
Also changing server size is not applied.

Eg.: 

Changing from `size: g3.k3s.xsmall` to `size: g3.k3s.medium` doesn't do anything. 
The size change is also not picked up when rescaling... 

So

```
count: 3
size: g3.k3s.xsmall
```

to

```
count: 1
size: g3.k3s.medium
``` 

does **not** take effect.
It is only rescaling but keeps the node size the same (in the example above it stays on `xsmall`)

**Comment by AlexsJones** [comment]
<img width="566" alt="Screenshot 2021-12-23 at 17 55 29" src="https://user-images.githubusercontent.com/1235925/147276367-f5522034-2ed3-4b1c-9d3e-a0a88580fe44.png">

Changing the node type is not supported as part of the rescaling of a node pool

**Comment by exocode** [comment]
@AlexsJones so, I then have to add a new nodepool, give it a new name, with a bigger server and set the other(old one) to zero? or delete it completely? Thank you

**Comment by AlexsJones** [comment]
If you want to change the machine types in a node pool from 
```
count: 3
size: g3.k3s.xsmall
```

to 
```
count: 3
size: g3.k3s. medium
```

I would just remove the old pool and add the new one

**Comment by DMajrekar** [comment]
This has been resolved in https://github.com/crossplane-contrib/provider-civo/pull/17
