### ISSUE TITLE
Create application from crossplane does not work

### ISSUE THREAD

**Issue by edalonso** [crossplane-contrib/provider-civo#44]
### What happened?
When I added application from CivoKubernetes kind from Crossplane, the application does not appear in the cluster and there is no error message.

### How can we reproduce it?
Create a cluster that include applications:

`kind: CivoKubernetes
apiVersion: cluster.civo.crossplane.io/v1alpha1
metadata:
  name: test-civo-crossplane
spec:
  name: test-civo-crossplane
  pools:
    - id: "8382e422-dcdd-461f-afb4-2ab67f171c3e"
      count: 1
      size: g3.k3s.xsmall
  applications:
    - "argo-cd"
  version: "1.23.6-k3s1"
  connectionDetails:
    connectionSecretNamePrefix: "cluster-details"
    connectionSecretNamespace: "default"
  providerConfigRef:
    name: civo-provider
`

I am not sure if there is low resource in the cluster, but there is no error in the kind Events:

![image](https://user-images.githubusercontent.com/4941133/220091160-c91f9f32-0cc0-4b24-a0e2-f7cd5f4be75d.png)

### What environment did it happen in?
Crossplane version: v1.11.0

**Comment by vishalanarase** [comment]
@edalonso Can you please test it again, we fixed some things in the backend.

**Comment by edalonso** [comment]
Hi @vishalanarase 

Solved!!

Thanks for the support.

**Comment by Vivekgaddigi** [comment]
if its solved then close this issue please
