### ISSUE TITLE
Left-over firewalls

### ISSUE THREAD

**Issue by vfarcic** [crossplane-contrib/provider-civo#6]
### What happened?

When creating a Kubernetes cluster, a firewall is created as well. However, after deleting a cluster, the firewall is left intact. The correct behavior should probably be that all the resources created with the cluster are deleted.

### How can we reproduce it?

Create a cluster using CivoKubernetes resources than delete it. Check the firewalls.

@AnaisUrlichs

**Comment by AnaisUrlichs** [comment]
Heya, I think this issues is resolved now. However, just to reiterate, we updated the cluster.yaml file in the examples folder to showcase how to provider the firewall id to a node pool. The reason that firewalls do not get deleted is that they are independent resources from your Kubernetes cluster. You could use the same firewall with its rules across multiple clusters.

**Comment by exocode** [comment]
@AnaisUrlichs in my case it is still left. Do I have to delete the provider too to remove the network?
