### ISSUE TITLE
Please recheck tutorials / functionality

### ISSUE THREAD

**Issue by exocode** [crossplane-contrib/provider-civo#7]
Hi there, Hi Anais, 
I watched a lot of videos from you and Victor (awesome thank you!) But now I stuck a bit:

Maybe you can point me to the right direction. Maybe it's a noob failure... Maybe I forgot a "switch". 

I am trying to follow your tutorial https://www.civo.com/learn/civo-crossplane-provider but I cannot get it working. I described my issue here: https://civo-community.slack.com/archives/C01EDL8C3B8/p1636928614252100

### What happened?
After tutorial completed (cluster deployed) I get an error
`UnknownError`

### How can we reproduce it?
Simply follow the tutorial / regular installation process. My issue appears when trying to apply the cluster itself.

### What environment did it happen in?

Civo

I followed the complete tutorial, I am using Civo cluster instead of a Kind cluster for Crossplane (I also tried Upbound (but that wont work either)). I get this error:

```
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2021-11-14T22:04:13Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2021-11-14T22:04:14Z
    Message:               create failed: UnknownError
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
  Message:
Events:
  Type     Reason                        Age                 From                                               Message
Warning  CannotCreateExternalResource  36s (x18 over 12m)  managed/civokubernetes.cluster.civo.crossplane.io  UnknownError

```

I tried different Helm charts too: (stable, main, devel) and versions 1.4, 1,5 `helm install crossplane --namespace crossplane-system --devel crossplane-master/crossplane --version 1.6.0-rc.0.41.g9a312374
`

`helm install crossplane --namespace crossplane-system crossplane-master/crossplane
`

`kubectl get all -n crossplane-system:`
```
NAME                                           READY   STATUS                  RESTARTS   AGE
pod/crossplane-rbac-manager-7c6ff4fd6f-82b5f   1/1     Running                 0          4m34s
pod/crossplane-69475c45c-rkp87                 0/1     Init:CrashLoopBackOff   5          4m34s

NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/crossplane                0/1     1            0           4m34s
deployment.apps/crossplane-rbac-manager   1/1     1            1           4m34s
Then I tried: 1.4.0 stable
Helm was deploying without errors, BUT the cluster creation does not work:
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2021-11-14T23:04:37Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2021-11-14T23:04:38Z
    Message:               create failed: UnknownError
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
  Message:
Events:
  Type     Reason                        Age                From                                               Message
  ----     ------                        ----               ----                                               -------
  Warning  CannotCreateExternalResource  32s (x6 over 64s)  managed/civokubernetes.cluster.civo.crossplane.io  UnknownError
and version 1.5 throws the same error:
Warning  CannotCreateExternalResource  7s (x8 over 2m14s)  managed/civokubernetes.cluster.civo.crossplane.io  UnknownError

```

Crossplane version: 

* Cloud provider or hardware configuration
  * Civo
* Kubernetes version (use `kubectl version`)
```
❯ k version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift)
  * `k3s ` from Civo
* 
* Kernel (e.g. `uname -a`) 
```
❯ uname -a
Darwin  20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

```
<img width="976" alt="bildschirmfoto_2021-11-15_um_02 00 46" src="https://user-images.githubusercontent.com/1597621/141868073-751881a6-9d87-4f1e-a4d2-4f5fb231a43b.png">

Any help would be AWESOME

Thank you in advance

**Comment by AnaisUrlichs** [comment]
Hey @exocode sorry for the delayed reply. It seems like this was an issue installing the Crossplane provider through the Helm chart? Please let me know if you are still running into this issue and I am going to try to get someone from Crossplane to look at it. Here are the steps that I follow when setting up my crossplane cluster:

Prerequisites: I just have a simple (medium) Civo Kubernetes cluster

```
kubectl create namespace crossplane-system

helm repo add crossplane-stable https://charts.crossplane.io/stable
helm repo update

helm install crossplane --namespace crossplane-system crossplane-stable/crossplane
```

Before proceding further, please make sure that all the crossplane resources are running:
`kubectl get all -n crossplane-system`

Next, I am providing the default provider.yaml and cluster.yaml in the examples directory of this repo through kubectl apply. Note that you have to update the API key in the provider.yaml with your own Civo API key.

Please let me know if anything is unclear. I am going to take another look at the guide.
